language: node_js

node_js:
  - "8.12.0"

notifications:
  webhooks: https://www.travisbuddy.com

cache: npm

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g polymer-cli

script:
  - polymer build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN